# Generated by Django 3.2.22 on 2023-10-18 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airlane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_1', models.CharField(max_length=256, verbose_name='From')),
                ('to', models.CharField(max_length=256, verbose_name='To')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('airlane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.airlane')),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('characteristics', models.CharField(blank=True, max_length=256, null=True, verbose_name='characteristics')),
                ('capacity', models.IntegerField(verbose_name='capacity')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.plane'),
        ),
        migrations.AddField(
            model_name='airlane',
            name='planes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.plane'),
        ),
    ]
